version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.http.routers.traefik.rule=PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik.service=api@internal"

  flask-app:
    build: ./app
    container_name: flask-app
    restart: always
    labels:
      - "traefik.http.routers.flask.rule=PathPrefix(`/`)"
      - "traefik.http.routers.flask.entrypoints=web"
